### ISSUE TITLE
Add configuration for output directory

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/FhirToCdm#1]

**Comment by bradanton** [comment]
Did you try -r?

FHIRtoCDM.exe -f E:\output\fhir -r **your_folder** -s dbo -v "Driver={SQL Server Native Client 11.0};Server=your_server;Database=db_name;Uid=user;Pwd=pswd;"

**Comment by fdefalco** [comment]
Sorry, no missed that. :(
