### ISSUE TITLE
non-standard concept identifiers used for types

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/FhirToCdm#6]
In the following tables a non-standard type concept is being used for the specified columns.  Please use 32817
condition_occurrence - condition_type_concept_id
drug_exposure - drug_type_concept_id
procedure_occurrence - procedure_type_concept_id
device_exposure - device_type_concept_id 
measurement - measurement_type_concept_id

using non-standard concept id.  please use 32817
https://athena.ohdsi.org/search-terms/terms/32817

**Comment by bradanton** [comment]
Fixed
