### ISSUE TITLE
Observation Resource Type not exported

### ISSUE THREAD

**Issue by Yusuf023** [OHDSI/FhirToCdm#7]
Hi,

I have a FHIR Bundle which I'm trying to convert into CDM. In that FHIR Bundle, I have the entries for resource type Patient, Encounter and Observation.
However, the Observation resource is not being exported. There is no error being displayed.
Following is the snippet of the FHIR Bundle (just the observation resource type)

Please let me know if I'm missing something

`{
         "fullUrl":"urn:uuid:cafb2106-1db9-3dd7-461f-1e75da976013",
         "resource":{
            "resourceType":"Observation",
            "id":"cafb2106-1db9-3dd7-461f-1e75da976013",
            "status":"final",
            "code":{
               "coding":[
                  {
                     "code":"31756-0",
                     "display":"PROTHROMBIN TIME",
                     "system":"http://loinc.org"
                  }
               ]
            },
            "valueQuantity":{
               "value":86575,
               "unit":"(kcal)/d"
            },
            "method":{
               "coding":[
                  {
                     "code":"VXC40",
                     "display":"Eligibility captured at the immunization level",
                     "system":"http://example.com/v2-to-fhir-converter/CodeSystem/CDCPHINVS"
                  }
               ]
            },
            "subject":{
               "reference":"Patient/7cae27a3-5724-1a37-fb13-afc83cf191f4"
            },
			"encounter": {
				"reference":"765abdc4-a622-729e-48e2-1f3d7934648c"
			},
			"effectiveDateTime":"2013-04-02T10:30:10+01:00",
            "extension":[
               {
                  "url":"http://example.com/v2-to-fhir-converter/Observation_Status",
                  "valueCodeableConcept":{
                     "coding":[
                        {
                           "code":"F",
                           "display":"Final",
                           "system":"http://terminology.hl7.org/CodeSystem/v2-0085"
                        }
                     ],
                     "text":"Final"
                  }
               }
            ]
         },
         "request":{
            "method":"PUT",
            "url":"Observation/cafb2106-1db9-3dd7-461f-1e75da976013"
         }
      },`

**Comment by bradanton** [comment]
Hi @Yusuf023 
"resourceType":"Observation" are exported to measurement table.
"resourceType":"AllergyIntolerance" to observation table.

**Comment by Yusuf023** [comment]
Hi @bradanton,

Thanks for the quick response. I do see data coming in the measurement table.

Can you please point me towards documentation which has information as to where data for each table is picked up from?

Additionally, is there a constraint that the parent resource type needs to be "Bundle"? Can single resources not be converted?

**Comment by bradanton** [comment]
@fdefalco do you know where can documentation be found?

@Yusuf023 yes, "Bundle" is required, single resources will not be converted.

**Comment by Yusuf023** [comment]
Thanks for the clarification @bradanton 

I am facing another issue - I have just started working on converting FHIR to CDM and  I haven't been able to get vocablury data. Since my lookup dictionary is empty, I am not seeing any value coming up for that specific code.
Would you happen to have any sample data for the vocablury tables so that they can be loaded to the lookup dictionary?

@fdefalco Please let me know of any documentation that can help with understanding where data for each table is picked up from.

Hugely appreciate all the help!

**Comment by bradanton** [comment]
@Yusuf023 

The lookup dictionary can be donloaded here: https://athena.ohdsi.org/
The tool uses following vocabularies: 'cvx', 'loinc', 'rxnorm', 'snomed', 'ucum'

**Comment by Yusuf023** [comment]
Thanks @bradanton!
